### ISSUE TITLE
Crash Issue

### ISSUE THREAD

**Issue by dennyxD** [HeberonYT/APM5#48]
Hola @HeberonYT , aquí dejo este crasheo que me ocurre aveces seguidamente, la ultima vez pude jugar por alrededor de 15minutos andes del crasheo. Espero me puedas ayudar, Gracias.

---- Minecraft Crash Report ----
// Why did you do that?

Time: 28/01/17 12:16 AM
Description: Exception ticking world

java.lang.IllegalArgumentException: Data value id is too big with 33! (Max is 31)
	at net.minecraft.entity.DataWatcher.func_75682_a(SourceFile:61)
	at com.hackshop.ultimate_unicorn.mobs.EntityMagicalHorse.func_70088_a(EntityMagicalHorse.java:505)
	at net.minecraft.entity.Entity.<init>(Entity.java:175)
	at net.minecraft.entity.EntityLivingBase.<init>(EntityLivingBase.java:119)
	at net.minecraft.entity.EntityLiving.<init>(EntityLiving.java:91)
	at net.minecraft.entity.EntityCreature.<init>(SourceFile:23)
	at net.minecraft.entity.EntityAgeable.<init>(SourceFile:17)
	at net.minecraft.entity.passive.EntityAnimal.<init>(SourceFile:26)
	at net.minecraft.entity.passive.EntityHorse.<init>(EntityHorse.java:85)
	at com.hackshop.ultimate_unicorn.mobs.EntityMagicalHorse.<init>(EntityMagicalHorse.java:449)
	at com.hackshop.ultimate_unicorn.mobs.EntityUnicorn.<init>(EntityUnicorn.java:15)
	at com.hackshop.ultimate_unicorn.mobs.EntityKnightVagabond.func_110161_a(EntityKnightVagabond.java:165)
	at net.minecraft.world.SpawnerAnimals.func_77192_a(SpawnerAnimals.java:267)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:161)
	at WorldServerOF.func_72835_b(WorldServerOF.java:234)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:625)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.entity.DataWatcher.func_75682_a(SourceFile:61)
	at com.hackshop.ultimate_unicorn.mobs.EntityMagicalHorse.func_70088_a(EntityMagicalHorse.java:505)
	at net.minecraft.entity.Entity.<init>(Entity.java:175)
	at net.minecraft.entity.EntityLivingBase.<init>(EntityLivingBase.java:119)
	at net.minecraft.entity.EntityLiving.<init>(EntityLiving.java:91)
	at net.minecraft.entity.EntityCreature.<init>(SourceFile:23)
	at net.minecraft.entity.EntityAgeable.<init>(SourceFile:17)
	at net.minecraft.entity.passive.EntityAnimal.<init>(SourceFile:26)
	at net.minecraft.entity.passive.EntityHorse.<init>(EntityHorse.java:85)
	at com.hackshop.ultimate_unicorn.mobs.EntityMagicalHorse.<init>(EntityMagicalHorse.java:449)
	at com.hackshop.ultimate_unicorn.mobs.EntityUnicorn.<init>(EntityUnicorn.java:15)
	at com.hackshop.ultimate_unicorn.mobs.EntityKnightVagabond.func_110161_a(EntityKnightVagabond.java:165)
	at net.minecraft.world.SpawnerAnimals.func_77192_a(SpawnerAnimals.java:267)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:161)
	at WorldServerOF.func_72835_b(WorldServerOF.java:234)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:625)

-- Affected level --
Details:
	Level name: Argentina
	All players: 1 total; [EntityPlayerMP['dennyxD'/254, l='Argentina', x=-657,50, y=18,00, z=661,54]]
	Chunk stats: ServerChunkCache: 882 Drop: 0
	Level seed: -488250169
	Level generator: ID 04 - BIOMESOP, ver 0. Features enabled: true
	Level generator options: 
	Level spawn location: World: (556,64,961), Chunk: (at 12,4,1 in 34,60; contains blocks 544,0,960 to 559,255,975), Region: (1,1; contains chunks 32,32 to 63,63, blocks 512,0,512 to 1023,255,1023)
	Level time: 111433 game time, 111433 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 62802 (now: false), thunder time: 27245 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 478586544 bytes (456 MB) / 1519632384 bytes (1449 MB) up to 4281597952 bytes (4083 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 15, tallocated: 96
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 Optifine OptiFine_1.7.10_HD_U_D6 94 mods loaded, 94 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAA	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAA	BRCore{1.0} [BRCore] (minecraft.jar) 
	UCHIJAAAA	CodeChickenCore{1.0.7.47} [CodeChicken Core] (minecraft.jar) 
	UCHIJAAAA	Micdoodlecore{} [Micdoodle8 Core] (minecraft.jar) 
	UCHIJAAAA	NotEnoughItems{1.0.5.120} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.120-universal.jar) 
	UCHIJAAAA	OpenModsCore{0.9.1} [OpenModsCore] (minecraft.jar) 
	UCHIJAAAA	FastCraft{1.23} [FastCraft] (fastcraft-1.23.jar) 
	UCHIJAAAA	battlegear2{1.7.10} [Mine & Blade Battlegear 2 - Bullseye] (1.7.10-MB_Battlegear2-Bullseye-1.0.8.3.jar) 
	UCHIJAAAA	BuildCraft|Core{7.1.17} [BuildCraft] (buildcraft-7.1.17.jar) 
	UCHIJAAAA	BuildCraft|Silicon{7.1.17} [BC Silicon] (buildcraft-7.1.17.jar) 
	UCHIJAAAA	BuildCraft|Transport{7.1.17} [BC Transport] (buildcraft-7.1.17.jar) 
	UCHIJAAAA	BuildCraft|Factory{7.1.17} [BC Factory] (buildcraft-7.1.17.jar) 
	UCHIJAAAA	additionalpipes{4.7.0} [Additional Pipes] (additionalpipes-4.7.2.jar) 
	UCHIJAAAA	advancedcapes{1.5} [Advanced Capes] (advancedcapes-1.5.jar) 
	UCHIJAAAA	AnimationAPI{1.2.4} [AnimationAPI] (AnimationAPI-1.7.10-1.2.4.jar) 
	UCHIJAAAA	Aquaculture{1.2.6} [Aquaculture] (Aquaculture-1.7.10-1.2.6.21.jar) 
	UCHIJAAAA	aquaticabyss{1.1.1} [Aquatic Abyss] (AquaticAbyss-1.7.10-1.1.1.jar) 
	UCHIJAAAA	ateliercanvas{0.2.0} [Atelier Canvas] (AtelierCanvas[1.7.10]-0.2.0.jar) 
	UCHIJAAAA	atum{0.6} [Atum] (Atum-1.7.10-0.6.77.jar) 
	UCHIJAAAA	BiblioCraft{1.11.5} [BiblioCraft] (BiblioCraft[v1.11.5][MC1.7.10].jar) 
	UCHIJAAAA	BiomesOPlenty{2.1.0} [Biomes O' Plenty] (BiomesOPlenty-1.7.10-2.1.0.2027-universal.jar) 
	UCHIJAAAA	blockarmor{1.1} [Block Armor] (BlockArmor-1.7.10-1.1.jar) 
	UCHIJAAAA	bookshelf{1.0.4.187} [Bookshelf] (Bookshelf-1.7.10-1.0.4.187.jar) 
	UCHIJAAAA	BottledAnimals{1.7.10-1.1.2} [Bottled Animals] (BottledAnimals-1.7.10-1.1.2.jar) 
	UCHIJAAAA	BrandonsCore{1.0.0.12} [Brandon's Core] (BrandonsCore-1.0.0.12.jar) 
	UCHIJAAAA	BuildCraft|Builders{7.1.17} [BC Builders] (buildcraft-7.1.17.jar) 
	UCHIJAAAA	BuildCraft|Energy{7.1.17} [BC Energy] (buildcraft-7.1.17.jar) 
	UCHIJAAAA	BuildCraft|Robotics{7.1.17} [BC Robotics] (buildcraft-7.1.17.jar) 
	UCHIJAAAA	cannibalism{1.3.0} [Cannibalism] (Cannibalism-1.3.0-1.7.10.jar) 
	UCHIJAAAA	CarpentersBlocks{3.3.8} [Carpenter's Blocks] (Carpenter's Blocks v3.3.8 - MC 1.7.10.jar) 
	UCHIJAAAA	cfm{3.4.8} [§9MrCrayfish's Furniture Mod] (cfm-3.4.8-mc1.7.10.jar) 
	UCHIJAAAA	CC2{2.58} [ChaosCraft] (Chaoscraft 1.7.10-2.58.jar) 
	UCHIJAAAA	chocolateQuest{1.0} [Chocolate Quest] (chocolateQuest-1.7.10-1.1d.jar) 
	UCHIJAAAA	christmastrees{1.0} [Decoratable Christmas Trees Mod] (christmastrees-1.0.jar) 
	UCHIJAAAA	CTBMod{1.7.10-0.2.1.27} [Creatubbles Mod] (CTBMod-1.7.10-0.2.1.27.jar) 
	UCHIJAAAA	customnpcs{1.7.10d} [CustomNpcs] (CustomNPCs_1.7.10d(21feb16).jar) 
	UCHIJAAAA	D3Core{1.1.2.41} [D3Core] (D3Core-1.7.10-1.1.2.41.jar) 
	UCHIJAAAA	DamageIndicatorsMod{3.2.0} [Damage Indicators] (Damage Indicators 1.7.10.jar) 
	UCHIJAAAA	dd{1.11} [Dragon Egg Replicator] (Dragon Egg Replicator mod-1.7.10-1.11.jar) 
	UCHIJAAAA	dragonrealm{1.1} [Dragon Realm] (DragonRealm_v1.2.jar) 
	UCHIJAAAA	MoCreatures{6.3.1} [DrZhark's Mo'Creatures Mod] (DrZharks MoCreatures Mod v6.3.1.zip) 
	UCHIJAAAA	DynamicCraft{1.1.4} [Dynamic Craft] (DynamicCraft-1.7.10-1.1.4.jar) 
	UCHIJAAAA	eplus{3.0.2-d} [Enchanting Plus] (EnchantingPlus-1.7.10-3.0.2-d.jar) 
	UCHIJAAAA	endercore{1.7.10-0.2.0.38_beta} [EnderCore] (EnderCore-1.7.10-0.2.0.38_beta.jar) 
	UCHIJAAAA	IC2{2.2.825-experimental} [IndustrialCraft 2] (industrialcraft-2-2.2.825-experimental.jar) 
	UCHIJAAAA	Forestry{4.2.15.63} [Forestry for Minecraft] (forestry_1.7.10-4.2.15.63.jar) 
	UCHIJAAAA	llibrary{1.5.1} [LLibrary] (llibrary-1.5.1-1.7.10.jar) 
	UCHIJAAAA	fossil{7.3.2} [Fossils and Archeology Revival] (fossilsarcheology-7.3.2.jar) 
	UCHIJAAAA	GalacticraftCore{3.0.12} [Galacticraft Core] (GalacticraftCore-1.7-3.0.12.375.jar) 
	UCHIJAAAA	GalacticraftMars{3.0.12} [Galacticraft Planets] (Galacticraft-Planets-1.7-3.0.12.375.jar) 
	UCHIJAAAA	hammertime{Hammer Time-1.7.10-1.3.6} [Hammer Time!] (HammerTime-1.3.6.jar) 
	UCHIJAAAA	journeymap{5.1.4p1} [JourneyMap] (journeymap-1.7.10-5.1.4p1-unlimited.jar) 
	UCHIJAAAA	lom{1.7.10-3.2.2} [LotsOMobs] (lom-1.7.10-3.2.2.jar) 
	UCHIJAAAA	malisiscore{1.7.10-0.14.3} [MalisisCore] (malisiscore-1.7.10-0.14.3.jar) 
	UCHIJAAAA	malisisdoors{1.7.10-1.13.2} [Malisis' Doors] (malisisdoors-1.7.10-1.13.2.jar) 
	UCHIJAAAA	RadixCore{2.1.3} [RadixCore] (RadixCore-1.7.10-2.1.3-universal.jar) 
	UCHIJAAAA	MCA{1.7.10-5.2.2} [Minecraft Comes Alive] (MCA-1.7.10-5.2.2-universal.jar) 
	UCHIJAAAA	MedicineCraft{V4.0} [MedicineCraft] (MedicineCraft V4.2.jar) 
	UCHIJAAAA	mfs{6.0.0} [Minecraft Flight Simulator] (Minecraft Flight Simulator-1.7.10-6.0.0.jar) 
	UCHIJAAAA	bettercraft{2.7.4} [MoreCraft] (MoreCraft-1.7.10-2.7.4.jar) 
	UCHIJAAAA	necromancy{1.7.2} [Necromancy] (Necromancy-1.7.10.jar) 
	UCHIJAAAA	NEIAddons{1.12.14.40} [NEI Addons] (neiaddons-1.12.14.40-mc1.7.10.jar) 
	UCHIJAAAA	NEIAddons|Developer{1.12.14.40} [NEI Addons: Developer Tools] (neiaddons-1.12.14.40-mc1.7.10.jar) 
	UCHIJAAAA	NEIAddons|AppEng{1.12.14.40} [NEI Addons: Applied Energistics 2] (neiaddons-1.12.14.40-mc1.7.10.jar) 
	UCHIJAAAA	NEIAddons|Botany{1.12.14.40} [NEI Addons: Botany] (neiaddons-1.12.14.40-mc1.7.10.jar) 
	UCHIJAAAA	NEIAddons|Forestry{1.12.14.40} [NEI Addons: Forestry] (neiaddons-1.12.14.40-mc1.7.10.jar) 
	UCHIJAAAA	NEIAddons|CraftingTables{1.12.14.40} [NEI Addons: Crafting Tables] (neiaddons-1.12.14.40-mc1.7.10.jar) 
	UCHIJAAAA	NEIAddons|ExNihilo{1.12.14.40} [NEI Addons: Ex Nihilo] (neiaddons-1.12.14.40-mc1.7.10.jar) 
	UCHIJAAAA	neiintegration{1.1.2} [NEI Integration] (NEIIntegration-MC1.7.10-1.1.2.jar) 
	UCHIJAAAA	recipehandler{1.7.10} [NoMoreRecipeConflict] (NoMoreRecipeConflict-0.3(1.7.10).jar) 
	UCHIJAAAA	Oceancraft{1.4.1} [Oceancraft] (Oceancraft-1.4.1.jar) 
	UCHIJAAAA	OpenMods{0.9.1} [OpenMods] (OpenModsLib-1.7.10-0.9.1.jar) 
	UCHIJAAAA	OpenBlocks{1.5.1} [OpenBlocks] (OpenBlocks-1.7.10-1.5.1.jar) 
	UCHIJAAAA	PlaceableTools{1.2.0.33} [PlaceableTools] (PlaceableTools-1.7.10-1.2.0.33.jar) 
	UCHIJAAAA	runicdungeons{1.1.7b} [Runic Dungeons] (RunicDungeons-1.1.7b.jar) 
	UCHIJAAAA	SimilsaxTranstructors{1.7.10.15} [Similsax Transtructors] (SimilsaxTranstructors-1.7.10.15.jar) 
	UCHIJAAAA	SlimeCarnage{1.0.5} [Slime Carnage] (SlimeCarnage-1.0.5d-mc1.7.10.jar) 
	UCHIJAAAA	StorageDrawers{1.7.10-1.10.1} [Storage Drawers] (StorageDrawers-1.7.10-1.10.1.jar) 
	UCHIJAAAA	TextureGeneratorLib{0.2} [TextureGeneratorLib] (TextureGeneratorLib-1.7.10_vBeta2.jar) 
	UCHIJAAAA	thebetweenlands{1.0.6-alpha} [The Betweenlands] (TheBetweenlands-1.0.6-alpha-universal.jar) 
	UCHIJAAAA	Waila{1.5.10} [Waila] (Waila-1.5.10_1.7.10.jar) 
	UCHIJAAAA	totemic{1.7.10-0.6.2} [Totemic] (Totemic-1.7.10-0.6.2.jar) 
	UCHIJAAAA	TragicMC{2.46.2878} [TragicMC 2] (TragicMC2-1.7.10-2.46.2878.jar) 
	UCHIJAAAA	turtle{1.7.10} [Trotuman] (Trotuman_1.7.10.jar) 
	UCHIJAAAA	ultimate_unicorn_mod{1.5.2} [Wings, Horns, and Hooves, the Ultimate Unicorn Mod!] (ultimate_unicorn_mod-1.7.10-1.5.2.jar) 
	UCHIJAAAA	aziasvendingmachine{Vending Machines Revamped} [Vending Machines Revamped] (VendingMachinesRevamped_1.1.0_1.7.10.jar) 
	UCHIJAAAA	wailaplugins{MC1.7.10-0.2.0-23} [WAILA Plugins] (WAILAPlugins-MC1.7.10-0.2.0-23.jar) 
	UCHIJAAAA	waystones{1.0.4} [Waystones] (Waystones-mc1.7.10-1.0.4.jar) 
	UCHIJAAAA	thejungle{1.0} [Welcome to the Jungle] (WelcomeToTheJungle-1.0.6alt-1.7.10.jar) 
	UCHIJAAAA	wc{2.1.0} [Wither Crown] (WitherArmor-2.1.0-mc1.7.10.jar) 
	UCHIJAAAA	WTFCore{1.7} [WhiskyTangoFox's Core] (WTFCore-1.7.10_v1.7.jar) 
	UCHIJAAAA	CaveBiomes{1.6} [WhiskyTangoFox's CaveBiomes] (WTFCaveBiomes-1.7.10_v1.6.jar) 
	OpenModsLib class transformers: [stencil_patches:FINISHED],[movement_callback:FINISHED],[map_gen_fix:FINISHED],[gl_capabilities_hook:FINISHED],[player_render_hook:FINISHED]
	Class transformer null safety: all safe
	Stencil buffer state: Function set: GL30, pool: internal, bits: 8
	Forestry : Warning: You have mods that change the behavior of Minecraft, ForgeModLoader, and/or Minecraft Forge to your client: 
Optifine
These may have caused this error, and may not be supported. Try reproducing the crash WITHOUT these mods, and report it then.
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Player Count: 1 / 8; [EntityPlayerMP['dennyxD'/254, l='Argentina', x=-657,50, y=18,00, z=661,54]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	OptiFine Version: OptiFine_1.7.10_HD_U_D6
	Render Distance Chunks: 12
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	OpenGlVersion: 4.5.13399 Compatibility Profile Context 15.201.1151.1010
	OpenGlRenderer: AMD Radeon HD 5700 Series
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 4

**Comment by HeberonYT** [comment]
Parece ser un problema de configuración de mods, por favor descarga el siguiente archivo y colócalo en tu carpeta **`.minecraft/config/`** 
Te preguntara si deseas reemplazar, presionas que si.

`http://www.mediafire.com/file/riuu1pkx0y00ivq/ultimate_unicorn_mod.cfg`

**Comment by dennyxD** [comment]
Muchas Gracias @HeberonYT  , eres el mejor ;) ya voy a probarlo..

Edit: todo perfecto @HeberonYT , muchas gracias!, pero pude notar este fallo gráfico (solo ocurre al mirar en cierta dirección, cada cierto tiempo)
![2017-01-29_18 10 52](https://cloud.githubusercontent.com/assets/25398332/22408634/96c6f66c-e652-11e6-9152-ccd0d34ad1df.png)
